# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaana', '0002_auto_20171014_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.FileField(upload_to=''),
        ),
    ]
