# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 13:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gaana', '0003_auto_20171015_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='song',
            name='year',
        ),
    ]
