# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaana', '0004_auto_20171015_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_file',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
